# Generated by Django 5.0.6 on 2026-05-18 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nota_docente', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('nota_secretaria', models.TextField(blank=True, null=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_emergencia', to='users.docente')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to=settings.AUTH_USER_MODEL)),
                ('slot_horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_emergencia', to='schedules.slothorario')),
            ],
            options={
                'verbose_name': 'Solicitud de Emergencia',
                'verbose_name_plural': 'Solicitudes de Emergencia',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anio', models.SmallIntegerField()),
                ('tipo_clase', models.CharField(choices=[('presencial', 'Presencial'), ('virtual_sincronica', 'Virtual Sincrónica'), ('asincronica', 'Asincrónica')], max_length=20)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_validada', models.BooleanField(blank=True, null=True)),
                ('latitud_registrada', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_registrada', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ip_registrada', models.CharField(blank=True, max_length=45, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='users.docente')),
                ('slot_horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='schedules.slothorario')),
                ('solicitud_emergencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='attendance.solicitudemergencia')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha', '-hora_entrada'],
                'unique_together': {('docente', 'slot_horario', 'fecha')},
            },
        ),
    ]
