# Generated by Django 5.0.6 on 2026-05-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
