# Generated by Django 5.0.6 on 2026-05-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_carrera_activo_slothorario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='codigo_siu',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
