# Generated by Django 5.0.6 on 2026-05-18 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_corte_mensual', models.SmallIntegerField(default=25)),
                ('red_wifi_campus', models.CharField(blank=True, max_length=100, null=True)),
                ('campus_latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('campus_longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('campus_radio_metros', models.SmallIntegerField(default=200)),
                ('metodo_validacion_ubicacion', models.CharField(choices=[('gps_o_wifi', 'GPS o WiFi'), ('solo_wifi', 'Solo WiFi'), ('solo_gps', 'Solo GPS')], default='gps_o_wifi', max_length=15)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
